### ISSUE TITLE
Custom validation message

### ISSUE THREAD

**Issue by ghost** [laravel-validation-rules/phone#2]
I need to provide custom validation message in validation. I can change it in vendor but I don't wan't to do id every time I updated composer.

**Comment by tylercd100** [comment]
Hello Samir,

I am on vacation until the 30th. If you need a solution sooner than that I
would be more than happy to review & merge a pull request from you

-Tyler

**Comment by ghost** [comment]
I extended main validation rules in AppServiceProvider.php
Don't forget to add Phone class to AppServiceProvider.php

```php
use LVR\Phone\Phone;
```
In boot() 

```php
Validator::extend('is_phone', function ($attribute, $value, $parameters, $validator) {
       $validate  = new Phone();
       return $validate->passes('',$value);
});
```

In your custom_rule.php in Rules: 
```php
   /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
	    return [
		    'phone' => 'required|string|is_phone',
	    ];
    }
```

So you can define custom message in the same custom_rule.php in Rules:

```php
  /**
   * Get the error messages for the defined validation rules.
   *
   * @return array
   */
   public function messages()
    {
         return [
                 'phone.is_phone' = 'Wrong phone number';
         ];
    }
```
