### ISSUE TITLE
Php 8 support

### ISSUE THREAD

**Issue by parth391** [laravel-validation-rules/phone#7]
Hello,

Getting error in php 8 as bellow:

`- Root composer.json requires laravel-validation-rules/phone ^1.5 -> satisfiable by laravel-validation-rules/phone[1.5.0].`
`- laravel-validation-rules/phone 1.5.0 requires php ^7.0 -> your php version (8.0.0) does not satisfy that requirement.`

**Comment by ssx** [comment]
Fixed in 57e7e801a14493068f435639104b5e56f000f221
